# Generated by Django 4.2 on 2023-11-04 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="auth_token",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_verified",
        ),
    ]
